<div align="center">
	<table border="2" cellspacing="0" cellpadding="15">
		<tr>
			<td>{{$n_name}}</td>
			<td>=</td>
			<td>{{$name}}</td>
		</tr>
		<tr>
			<td>{{$n_network}}</td>
			<td>=</td>
			<td>{{$network}}</td>
		</tr>
		<tr>
			<td>{{$n_version}}</td>
			<td>=</td>
			<td>{{$version}}</td>
		</tr>
		<tr>
			<td>{{$n_registrations_open}}</td>
			<td>=</td>
			<td>{{$registrations_open}}</td>
		</tr>
		<tr>
			<td>{{$n_total_users}}</td>
			<td>=</td>
			<td>{{$total_users}}</td>
		</tr>
		<tr>
			<td>{{$n_active_users_halfyear}}</td>
			<td>=</td>
			<td>{{$active_users_halfyear}}</td>
		</tr>
		<tr>
			<td>{{$n_active_users_monthly}}</td>
			<td>=</td>
			<td>{{$active_users_monthly}}</td>
		</tr>
		<tr>
			<td>{{$n_local_posts}}</td>
			<td>=</td>
			<td>{{$local_posts}}</td>
		</tr>
		<tr>
			<td>{{$n_appnet}}</td>
			<td>=</td>
			<td>{{$appnet}}</td>
		</tr>
		<tr>
			<td>{{$n_blogger}}</td>
			<td>=</td>
			<td>{{$blogger}}</td>
		</tr>
		<tr>
			<td>{{$n_buffer}}</td>
			<td>=</td>
			<td>{{$buffer}}</td>
		</tr>
		<tr>
			<td>{{$n_dreamwidth}}</td>
			<td>=</td>
			<td>{{$dreamwidth}}</td>
		</tr>
		<tr>
			<td>{{$n_facebook}}</td>
			<td>=</td>
			<td>{{$facebook}}</td>
		</tr>
		<tr>
			<td>{{$n_gnusocial}}</td>
			<td>=</td>
			<td>{{$gnusocial}}</td>
		</tr>
		<tr>
			<td>{{$n_googleplus}}</td>
			<td>=</td>
			<td>{{$googleplus}}</td>
		</tr>
		<tr>
			<td>{{$n_libertree}}</td>
			<td>=</td>
			<td>{{$libertree}}</td>
		</tr>
		<tr>
			<td>{{$n_livejournal}}</td>
			<td>=</td>
			<td>{{$livejournal}}</td>
		</tr>
		<tr>
			<td>{{$n_pumpio}}</td>
			<td>=</td>
			<td>{{$pumpio}}</td>
		</tr>
		<tr>
			<td>{{$n_twitter}}</td>
			<td>=</td>
			<td>{{$twitter}}</td>
		</tr>
		<tr>
			<td>{{$n_tumblr}}</td>
			<td>=</td>
			<td>{{$tumblr}}</td>
		</tr>
		<tr>
			<td>{{$n_wordpress}}</td>
			<td>=</td>
			<td>{{$wordpress}}</td>
		</tr>
	</table>
</div>
