#### DON'T EDIT THIS FILE AT ROOT, use /view/templates/mkdocs.yaml.tpl Template ####
# Copyright (C) 2010-2022, the Friendica project

# GNU AGPL version 3 or any later version

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.

# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# Project information
site_name: Friendica documentation
site_url: https://friendi.ca
site_author: The Friendica project
site_description: >-
  Friendica is a decentralised communications platform that integrates social communication.
  Our platform links to independent social projects and corporate services.
docs_dir: doc

# Repository
repo_url: https://github.com/friendica/friendica
repo_name: friendica/friendica
edit_uri: edit/develop/doc/

use_directory_urls: true

# Copyright
copyright: Copyright &copy; 2010-2022, the Friendica project

# Configuration
theme:
  name: 'material'
  icon:
    repo: fontawesome/brands/github

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    - content.code.annotate
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate

  logo: assets/images/friendica.svg
  favicon: assets/images/friendica-32.png
plugins:
  - search
  - tags
  - i18n:
      default_language: en
      docs_structure: folder
      languages:
        en:
          name: English
          build: true
        de:
          name: Deutsch
          build: true
          site_name: Friendica Dokumentation
      nav_translations:
        de:
          User: Benutzer
          Quick Start: Schnellstart
          'Bugs and Issues': 'Bugs und Probleme'
          Configuration: Konfiguration
          Third Party: Dritthersteller
          'First Steps': Erste Schritte
          'You and other users': Du mit anderen Nutzer
          'Further information': Weiterführende Informationen

extra:
  homepage: https://friendi.ca

extra_css:
  - assets/stylesheets/friendica.css

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      permalink: "#"

nav:
  - En:
    - index.md
    - User:
      - First Steps:
        - user/account-basics.md
        - Quick Start:
          - user/quick-start/guide.md
          - user/quick-start/network.md
          - user/quick-start/groups-and-pages.md
          - user/quick-start/making-new-friends.md
          - user/quick-start/finally.md
        - user/text-editor.md
        - user/bbcode.md
        - user/text-comment.md
        - user/accesskeys.md
        - user/events.md
        - user/keyboard-shortcuts.md
      - You and other users:
        - user/connectors.md
        - user/making-friends.md
        - user/groups-and-privacy.md
        - user/tags-and-mentions.md
        - user/forums.md
        - user/chats.md
      - Further information:
        - user/move-account.md
        - user/export-import-contacts.md
        - user/remove-account.md
        - user/two-factor-authentication.md
        - user/faq.md
    - Admin:
      - Installation:
        - admin/install.md
        - admin/update.md
        - admin/migrate.md
      - Configuration:
        - admin/settings.md
        - admin/config.md
        - admin/ssl.md
        - admin/improve-performance.md
        - admin/tools.md
      - Third Party:
        - admin/installing-connectors.md
        - admin/install-ejabberd.md
      - admin/faq.md
    - Developer:
        - developer/index.md
        - Set Up:
          - developer/github.md
          - developer/vagrant.md
        - Code structure:
          - developer/domain-driven-design.md
          - developer/addons.md
          - developer/themes.md
          - developer/smarty3-templates.md
          - developer/addon-storage-backend.md
        - How To:
          - developer/translations.md
          - developer/composer.md
          - developer/how-to-move-classes-to-src.md
          - developer/tests.md
          - developer/autoloader.md
        - Specification:
          - API:
            - spec/api/index.md
            - spec/api/entities.md
            - spec/api/friendica.md
            - spec/api/mastodon.md
            - spec/api/twitter.md
            - spec/api/gnu-social.md
          - Database:
            - spec/database/index.md
            - spec/database/db_2fa_app_specific_password.md
            - spec/database/db_2fa_recovery_codes.md
            - spec/database/db_2fa_trusted_browser.md
            - spec/database/db_addon.md
            - spec/database/db_apcontact.md
            - spec/database/db_application.md
            - spec/database/db_application-marker.md
            - spec/database/db_application-token.md
            - spec/database/db_attach.md
            - spec/database/db_cache.md
            - spec/database/db_config.md
            - spec/database/db_contact.md
            - spec/database/db_contact-relation.md
            - spec/database/db_conv.md
            - spec/database/db_conversation.md
            - spec/database/db_delayed-post.md
            - spec/database/db_diaspora-interaction.md
            - spec/database/db_endpoint.md
            - spec/database/db_event.md
            - spec/database/db_fcontact.md
            - spec/database/db_fsuggest.md
            - spec/database/db_group.md
            - spec/database/db_group_member.md
            - spec/database/db_gserver.md
            - spec/database/db_gserver-tag.md
            - spec/database/db_hook.md
            - spec/database/db_inbox-entry.md
            - spec/database/db_inbox-entry-receiver.md
            - spec/database/db_inbox-status.md
            - spec/database/db_intro.md
            - spec/database/db_item-uri.md
            - spec/database/db_locks.md
            - spec/database/db_mail.md
            - spec/database/db_mailacct.md
            - spec/database/db_manage.md
            - spec/database/db_notification.md
            - spec/database/db_notify.md
            - spec/database/db_notify-threads.md
            - spec/database/db_oembed.md
            - spec/database/db_openwebauth-token.md
            - spec/database/db_parsed_url.md
            - spec/database/db_pconfig.md
            - spec/database/db_permissionset.md
            - spec/database/db_photo.md
            - spec/database/db_post.md
            - spec/database/db_post-category.md
            - spec/database/db_post-collection.md
            - spec/database/db_post-content.md
            - spec/database/db_post-delivery.md
            - spec/database/db_post-delivery-data.md
            - spec/database/db_post-history.md
            - spec/database/db_post-link.md
            - spec/database/db_post-media.md
            - spec/database/db_post-question.md
            - spec/database/db_post-question-option.md
            - spec/database/db_post-tag.md
            - spec/database/db_post-thread.md
            - spec/database/db_post-thread-user.md
            - spec/database/db_post-user.md
            - spec/database/db_post-user-notification.md
            - spec/database/db_process.md
            - spec/database/db_profile.md
            - spec/database/db_profile_field.md
            - spec/database/db_push_subscriber.md
            - spec/database/db_register.md
            - spec/database/db_search.md
            - spec/database/db_session.md
            - spec/database/db_storage.md
            - spec/database/db_subscription.md
            - spec/database/db_tag.md
            - spec/database/db_user.md
            - spec/database/db_user-contact.md
            - spec/database/db_userd.md
            - spec/database/db_verb.md
            - spec/database/db_worker-ipc.md
            - spec/database/db_workerqueue.md
          - Protocol:
            - spec/protocol/protocol.md
            - spec/protocol/message-flow.md
    - 'Bugs and Issues': bugs-and-issues.md
