{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}
<a id="toggle_mobile_link" href="{{$toggle_link}}"><img src="/images/icons/22/toggle_mobile.png" /></a>
