#depends_on:
#  - phpunit
#  - code_standards_check

# This prevents executing this pipeline at other servers than ci.friendi.ca
labels:
  type: releaser
  location: friendica

pipeline:
  clone_friendica_help:
    image: alpine/git
    commands:
      - git clone https://ci.friendica.ca/nupplaPhil/help.git help
      - git checkout -b {CI_COMMIT_BRANCH}
  restore_cache:
    image: meltwater/drone-cache:dev
    settings:
      backend: "filesystem"
      restore: true
      cache_key: "{{ .Repo.Name }}_php7.4_{{ arch }}_{{ os }}"
      archive_format: "gzip"
      mount:
        - '.composer'
    volumes:
      - /tmp/drone-cache:/tmp/cache
  composer_install:
    image: friendicaci/php7.4:php7.4.18
    commands:
      - export COMPOSER_HOME=.composer
      - ./bin/composer.phar validate
      - ./bin/composer.phar install --no-dev --optimize-autoloader
    volumes:
      - /etc/hosts:/etc/hosts
  update_makefiles:
    image: friendicaci/php7.4:php7.4.18
    commands:
      - ./bin/console createdocumentation createMkDocs
  create_documentation:
    image: friendicaci/mkdocs
    commands:
      - rm -fr help/*
      - mkdocs build -d help
  commit:
    image: alpine/git
    secrets:
      - source: help-username
        target: help_username
      - source: help-password
        target: help_password
    commands:
      - cd help/
      - git add .
      - git commit -m "${CI_COMMIT_LINK}"
      - git push https://$HELP_USERNAME:$HELP_PASSWORD@ci.friendica.ca/nupplaPhil/help.git --all
  publish:
    image: alpine
    commands:
      - mkdir -p /tmp/friendica_docs/${CI_COMMIT_BRANCH}
      - rm -fr /tmp/friendica_docs/${CI_COMMIT_BRANCH}/*
      - cp -fr ./help/* /tmp/friendica_docs/${CI_COMMIT_BRANCH}/
    volumes:
      - docs:/tmp/friendica_docs
